#!/usr/bin/env bash
# To configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# To Configure haproxy configuration file to distribute requests
using a roundrobin algorithm echo '
frontend kerado.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 480975-web-01 18.210.15.47:80
        server 480975-web-02 107.23.109.127:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
