#!/usr/bin/env bash
# A function that displays list of currently running processes
# It Must show all processes, for all users, including those which might not have a TTY
# It displays a user-oriented format
# It will show process hierarchy

ps -a -x -u -f
